development:
  clients:
    default:
      uri: <%= ENV['MONGO_URL'] %>

test:
  clients:
    default:
      database: fetedelamusique_test
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1

production:
  clients:
    default:
      uri: <%= ENV['MONGO_URL'] %>
